countdown module created
pumpkin-py/pumpkin-reminder pull request #27
Opened 2022-10-25 19:16 UTC by 418m

2022-10-25 20:05 UTC, ArcasCZ reviewed
Overall the code looks good, it's easy to read and I don't see any spaghetti code there.

2022-10-25 20:05 UTC, ArcasCZ commented on countdown/module.py
> +        if date < datetime.now():
Since you are throwing ValueError, you might also use try-except block.

2022-10-25 20:05 UTC, ArcasCZ commented on countdown/module.py
> +    async def _process_text(self, ctx: commands.Context, text: Optional[str]):
This should be a utils function in pumpkin-py core. I think I've seen this kind of code in other modules / pumpkin-py repos.

2022-10-28 16:56 UTC, sinus-x requested changes
The code looks good, I have some minor requests.

2022-10-28 16:56 UTC, sinus-x commented on countdown/database.py
> +    __tablename__ = "fun_countdown_countdownitem"
This could be just `fun_countdown_item`

2022-10-28 16:56 UTC, sinus-x commented on countdown/database.py
> +        idx: int = None,
1/ Do we need to filer by idx?
2/ I'd prefer if database files worked directly with `guild_id`, not DIscord objects. This is different from how the rest of the codebase is done.

2022-10-28 16:56 UTC, sinus-x commented on countdown/database.py
> +        author: discord.Member = None,
Same here, IDs instead of objects.

2022-10-28 16:56 UTC, sinus-x commented on countdown/module.py
> +    async def _process_text(self, ctx: commands.Context, text: Optional[str]):
I'd like to see some docstring, describing what the function does to the text.

2022-10-28 16:56 UTC, sinus-x commented on countdown/module.py
> +    async def _get_member(self, user_id: int, guild_id: int = 0):
Yep, it can go.

2022-10-28 16:56 UTC, sinus-x commented on countdown/module.py
> +            countdown = CountdownDummy()
You don't need to create new class, in Python you can just add attributes into new `countdown = object()`

2022-10-28 18:52 UTC, sinus-x requested changes

2022-10-28 18:52 UTC, sinus-x commented on countdown/database.py
> +        author_id: discord.Member = None,
The type hint should be `: int` now.

2022-10-28 18:55 UTC, 418m commented on countdown/database.py
> +        author_id: discord.Member = None,
Fixed

2022-10-28 19:42 UTC, sinus-x approved these changes
Checks have passed, I'm gonna assume it is fine.

2022-10-28 19:42 UTC, merged