Reschedule displays also original date (#25)
pumpkin-py/pumpkin-reminder pull request #28
Opened 2022-10-25 19:58 UTC by 418m

2022-10-25 20:08 UTC, ArcasCZ requested changes

2022-10-25 20:08 UTC, ArcasCZ commented on reminder/module.py
> +            name=_(ctx, "Original time"),
You have to run the popie, otherwise it won't pass the build as this won't be translated.

2022-10-28 16:31 UTC, sinus-x commented
Could you add the new values to .popie files manually? You can see where the PoPie tool would put them in the build output.

2022-10-28 17:21 UTC, 418m commented
Done

2022-10-28 17:43 UTC, merged